// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_RobotAgent_LogMessage(char* param0) { RobotAgent::LogMessage(param0); }
	inline void FunctionPointer_RobotAgent_SayHello(Agent* self) { ((RobotAgent*)self)->SayHello(); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
